### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by smviking** [Raymai97/OpenFolderAndSelectItem#2]
Hi, awesome little program. Any chance of wildcard support or just opening folders directly? I need it in order to fix my qttabbar window capture issues. 

`OpenFolderAndSelect.exe "C:\Users\Admin\Documents\*.*"`

In the example above I want to open the documents folder and select any file (not just open the admin folder).

Best regards

**Comment by Raymai97** [comment]
Hi @smviking 

Please try the latest release.
https://github.com/Raymai97/OpenFolderAndSelectItem/releases/tag/v2022.12.04

**Comment by smviking** [comment]
Amazing! Thank you so much. That fixed 99% of my problems.

I don't wanna bother you too much, but is there any way you could also add a character that would signify just navigating to a folder, without selecting anything?

`OpenFolderAndSelect.exe "C:\Users\Admin\Documents\EmptySubfolder\-"`
or maybe
`OpenFolderAndSelect.exe "C:\Users\Admin\Documents\EmptySubfolder\@"`

In the above example I would just like to navigate to "EmptySubfolder" without selecting anything.

Best regards

**Comment by Raymai97** [comment]
Hi @smviking 

If you want to open folder without selecting anything, there is a simpler way to achieve it I think.

If your program supports executing batch file, you may try batch file below:
```
OpenFolder C:\Windows
```
[OpenFolder.cmd.zip](https://github.com/Raymai97/OpenFolderAndSelectItem/files/10171190/OpenFolder.cmd.zip)

If your program does not support batch file, you could set it to run:
```
C:\Windows\system32\cmd.exe /c pushd "[folder path here]" & start.
```

**Comment by smviking** [comment]
Hi, sorry for not responding. You have been very helpful and I thank you very much.
