### ISSUE TITLE
Multiple specified files support

### ISSUE THREAD

**Issue by skygate2012** [Raymai97/OpenFolderAndSelectItem#4]
Can you make it take in a list of file names to select, not just a wildcard pattern?

**Comment by Raymai97** [comment]
Not understand. Please elaborate.

**Comment by skygate2012** [comment]
For example:
`OpenFolderAndSelect.exe "X:\xxx.txt" "X:\yyy.txt" "X:\zzz.txt"`

**Comment by Raymai97** [comment]
OK, I will try make it like `OpenFolderAndSelect.exe C:\Windows hh.exe explorer.exe` when I have time.

**Comment by Raymai97** [comment]
Hi @skygate2012 

Please try out the latest release.

**Comment by skygate2012** [comment]
Thank you so much! Works great 👏
