### ISSUE TITLE
Window not focusing and sometimes not opening when run from VBA

### ISSUE THREAD

**Issue by skygate2012** [Raymai97/OpenFolderAndSelectItem#5]
I seem to have encountered a potential bug. It only occurs in VBA.
If I run this:
```
Shell "path\to\OpenFolderAndSelect.exe C:\Windows\hh.exe"
```
Sometimes it will open the folder window and immediately minimize or close the window; other times it would not open the folder at all. If the folder is opened. It would switch the focus to that folder window but does not restore the window.

If I use cmd to run the binary it would work fine just like in any other environment.
```
Shell Environ$("COMSPEC") & " /c path\to\OpenFolderAndSelect.exe C:\Windows\hh.exe" ', vbHide
```

I tried the previous release, it seems to have the same issue.

**Comment by Raymai97** [comment]
Hi @skygate2012 

This sounds like VBA issue. Maybe Windows imposed restriction on VBA code?
I tried with VBS, seems fine.
```vbs
Set objShell = CreateObject("Wscript.Shell") 
objShell.Run "OpenFolderAndSelect.exe C:\Windows\hh.exe"
```

**Comment by skygate2012** [comment]
Well, it only happens in VBA. But I don't think it's a VBA issue. Earlier I made an AHK version of OpenFolderAndSelectItems and it worked fine in VBA with the following:
```
Shell "path\to\OpenFolderAndSelectItems.exe C:\Windows\hh.exe" ', vbHide
```
It's a weird one for sure. I don't really know where the issue originates.

Here's my AHK version if that helps:
[OpenFolderAndSelectItems.zip](https://github.com/Raymai97/OpenFolderAndSelectItem/files/14472099/OpenFolderAndSelectItems.zip)

**Comment by Raymai97** [comment]
Hi @skygate2012 

I have reproduced your issue in both virtual machine:
* Windows XP RTM + Office XP
* Windows 10 21H2 + Office 2016

I can specify vbNormalFocus to prevent this issue from happening, like:
```vba
Shell "C:\Windows\OpenFolderAndSelect.exe C:\Windows\hh.exe", vbNormalFocus
```

**Comment by skygate2012** [comment]
Ah I see, so in VBA the default window style for the Shell function is minimized with focus. Specifying vbNormalFocus works perfect now. Thanks!
